### ISSUE TITLE
Bug: can't get environment variable with dot

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#4026]
**Describe the bug**
We can't get environment variable that name has dot on some environment.
So we can't change Config values.

docker-compose.yml:
```
services:
  web:
    ...
    environment:
      - database.default.port=${DB_PORT:-3306}
      - database_default_port=${DB_PORT:-3306}
```

httpd.conf:
```
    PassEnv database.default.port
    PassEnv database_default_port
```

controller code:
```
dd(getenv('database.default.port')); // => false 
```

```
dd(getenv('database_default_port')); // => string 3306
```

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
Out of CodeIgniter?

**Expected behavior, and steps to reproduce if appropriate**
Environment variable name with dot is difficult to handle. It is better to support variable name without dot.

**Context**
 - OS: [Debian 10.7] Docker php:7.4-apache-buster
 - Web server [Apache 2.4.38-3+deb10u4]
 - PHP version [7.4.13]
