### ISSUE TITLE
Dev: userguide deployment fails

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#7464]
userguide deployment fails.

```
======CMD======
/opt/userguide/.github/scripts/deploy
======END======
2023/04/27 12:38:55 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
https://github.com/codeigniter4/userguide/actions/runs/4819849048/jobs/8583581649

**Comment by kenjis** [comment]
```
======CMD======
/opt/userguide/.github/scripts/deploy
======END======
2023/06/17 23:15:44 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
https://github.com/codeigniter4/userguide/actions/runs/5300609212/jobs/9594251861

**Comment by kenjis** [comment]
@MGatner @lonnieezell Can you create a new ssh key and register it to the server?
Old keys may not work with recent default server configurations for security reasons.

**Comment by kenjis** [comment]
```
======CMD======
/opt/userguide/.github/scripts/deploy
======END======
2023/08/25 01:48:52 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
https://github.com/codeigniter4/userguide/actions/runs/5970904542/job/16199189746

**Comment by kenjis** [comment]
https://github.com/codeigniter4/userguide/actions/runs/6078853508/job/16490588696
```
======CMD======
/opt/userguide/.github/scripts/deploy
======END======
2023/09/05 00:47:56 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by MGatner** [comment]
Is this the same issue as the website deployment failure?

**Comment by kenjis** [comment]
I don't know.
But this issue existed before the failure of the website deployment.

**Comment by kenjis** [comment]
https://github.com/codeigniter4/userguide/actions/runs/6580531877/job/17878705356
```
Run appleboy/ssh-action@master
  with:
    host: ***
    username: ***
    key: ***
    port: ***
    script: /opt/userguide/.github/scripts/deploy
    timeout: 30s
    command_timeout: 10m
    proxy_port: ***
    proxy_timeout: 30s
/usr/bin/docker run --name c5ac2759b6cf2a64b4baeb8eb5c925c92a3_ffa2e5 --label 428c5a --workdir /github/workspace --rm -e "INPUT_HOST" -e "INPUT_USERNAME" -e "INPUT_KEY" -e "INPUT_PORT" -e "INPUT_SCRIPT" -e "INPUT_PASSPHRASE" -e "INPUT_PASSWORD" -e "INPUT_SYNC" -e "INPUT_USE_INSECURE_CIPHER" -e "INPUT_CIPHER" -e "INPUT_TIMEOUT" -e "INPUT_COMMAND_TIMEOUT" -e "INPUT_KEY_PATH" -e "INPUT_FINGERPRINT" -e "INPUT_PROXY_HOST" -e "INPUT_PROXY_PORT" -e "INPUT_PROXY_USERNAME" -e "INPUT_PROXY_PASSWORD" -e "INPUT_PROXY_PASSPHRASE" -e "INPUT_PROXY_TIMEOUT" -e "INPUT_PROXY_KEY" -e "INPUT_PROXY_KEY_PATH" -e "INPUT_PROXY_FINGERPRINT" -e "INPUT_PROXY_CIPHER" -e "INPUT_PROXY_USE_INSECURE_CIPHER" -e "INPUT_SCRIPT_STOP" -e "INPUT_ENVS" -e "INPUT_ENVS_FORMAT" -e "INPUT_DEBUG" -e "INPUT_ALLENVS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/userguide/userguide":"/github/workspace" 428c5a:c2759b6cf2a64b4baeb8eb5c925c92a3
======CMD======
/opt/userguide/.github/scripts/deploy
======END======
err: Already on 'master'
out: Your branch is up to date with 'origin/master'.
err: From https://github.com/codeigniter4/userguide
err:    ad8e0ae..26a4d5f  master     -> origin/master
err:  * [new tag]         v4.4.2     -> v4.4.2
err:  * [new tag]         v4.4.1     -> v4.4.1
out: Updating ad8e0ae..26a4d5f
out: Fast-forward
out:  CodeIgniter4.4.1.epub                              | Bin 0 -> 1811556 bytes
out:  CodeIgniter4.4.2.epub                              | Bin 0 -> 1754543 bytes
out:  docs/.buildinfo                                    |   2 +-
out:  docs/_images/debugbar.png                          | Bin 81068 -> 23357 bytes
out:  docs/_images/tutorial3.png                         | Bin 47293 -> 39569 bytes
out:  docs/_images/tutorial4.png                         | Bin 30520 -> 25486 bytes
out:  docs/_images/welcome.png                           | Bin 176104 -> 146354 bytes
out:  docs/_static/documentation_options.js              |   2 +-
out:  docs/changelogs/index.html                         |  10 +-
out:  docs/changelogs/v4.0.0-alpha.1.html                |   4 +-
out:  docs/changelogs/v4.0.0-alpha.2.html                |   4 +-
out:  docs/changelogs/v4.0.0-alpha.3.html                |   4 +-
out:  docs/changelogs/v4.0.0-alpha.4.html                |   4 +-
out:  docs/changelogs/v4.0.0-alpha.5.html                |   4 +-
out:  docs/changelogs/v4.0.0-beta.1.html                 |   4 +-
out:  docs/changelogs/v4.0.0-beta.2.html                 |   4 +-
out:  docs/changelogs/v4.0.0-beta.3.html                 |   4 +-
out:  docs/changelogs/v4.0.0-beta.4.html                 |   4 +-
out:  docs/changelogs/v4.0.0-rc.1.html                   |   4 +-
out:  docs/changelogs/v4.0.0-rc.2.html                   |   4 +-
out:  docs/changelogs/v4.0.0-rc.3.html                   |   4 +-
out:  docs/changelogs/v4.0.0-rc.4.html                   |   4 +-
out:  docs/changelogs/v4.0.0.html                        |   4 +-
out:  docs/changelogs/v4.0.3.html                        |   4 +-
out:  docs/changelogs/v4.0.4.html                        |   4 +-
out:  docs/changelogs/v4.0.5.html                        |   4 +-
out:  docs/changelogs/v4.1.0.html                        |   4 +-
out:  docs/changelogs/v4.1.1.html                        |   4 +-
out:  docs/changelogs/v4.1.2.html                        |   4 +-
out:  docs/changelogs/v4.1.3.html                        |   4 +-
out:  docs/changelogs/v4.1.4.html                        |   4 +-
out:  docs/changelogs/v4.1.5.html                        |   4 +-
out:  docs/changelogs/v4.1.6.html                        |   4 +-
out:  docs/changelogs/v4.1.7.html                        |   4 +-
out:  docs/changelogs/v4.1.8.html                        |   4 +-
out:  docs/changelogs/v4.1.9.html                        |   4 +-
out:  docs/changelogs/v4.2.0.html                        |   4 +-
out:  docs/changelogs/v4.2.1.html                        |   4 +-
out:  docs/changelogs/v4.2.10.html                       |   4 +-
out:  docs/changelogs/v4.2.11.html                       |   4 +-
out:  docs/changelogs/v4.2.12.html                       |   4 +-
out:  docs/changelogs/v4.2.2.html                        |   4 +-
out:  docs/changelogs/v4.2.3.html                        |   4 +-
out:  docs/changelogs/v4.2.4.html                        |   4 +-
out:  docs/changelogs/v4.2.5.html                        |   4 +-
out:  docs/changelogs/v4.2.6.html                        |   4 +-
out:  docs/changelogs/v4.2.7.html                        |   4 +-
out:  docs/changelogs/v4.2.8.html                        |   4 +-
out:  docs/changelogs/v4.2.9.html                        |   4 +-
out:  docs/changelogs/v4.3.0.html                        |   4 +-
out:  docs/changelogs/v4.3.1.html                        |   4 +-
out:  docs/changelogs/v4.3.2.html                        |   4 +-
out:  docs/changelogs/v4.3.3.html                        |   4 +-
out:  docs/changelogs/v4.3.4.html                        |   4 +-
out:  docs/changelogs/v4.3.5.html                        |   4 +-
out:  docs/changelogs/v4.3.6.html                        |   4 +-
out:  docs/changelogs/v4.3.7.html                        |   4 +-
out:  docs/changelogs/v4.3.8.html                        |   4 +-
out:  docs/changelogs/v4.4.0.html                        |   9 +-
out:  docs/changelogs/v4.4.1.html                        | 342 +++++++++++++++++++
out:  docs/changelogs/v4.4.2.html                        | 371 +++++++++++++++++++++
out:  docs/cli/cli_commands.html                         |   4 +-
out:  docs/cli/cli_controllers.html                      |   4 +-
out:  docs/cli/cli_generators.html                       |   4 +-
out:  docs/cli/cli_library.html                          |   4 +-
out:  docs/cli/cli_overview.html                         |   4 +-
out:  docs/cli/cli_request.html                          |   4 +-
out:  docs/cli/index.html                                |   4 +-
out:  docs/cli/spark_commands.html                       |   4 +-
out:  docs/concepts/autoloader.html                      |   4 +-
out:  docs/concepts/factories.html                       |   4 +-
out:  docs/concepts/http.html                            |   4 +-
out:  docs/concepts/index.html                           |   4 +-
out:  docs/concepts/mvc.html                             |   4 +-
out:  docs/concepts/security.html                        |   4 +-
out:  docs/concepts/services.html                        |   4 +-
out:  docs/concepts/structure.html                       |   4 +-
out:  docs/database/call_function.html                   |   4 +-
out:  docs/database/configuration.html                   |   6 +-
out:  docs/database/connecting.html                      |   4 +-
out:  docs/database/events.html                          |   4 +-
out:  docs/database/examples.html                        |   4 +-
out:  docs/database/helpers.html                         |   4 +-
out:  docs/database/index.html                           |   4 +-
out:  docs/database/metadata.html                        |   4 +-
out:  docs/database/queries.html                         |   4 +-
out:  docs/database/query_builder.html                   |   4 +-
out:  docs/database/results.html                         |   4 +-
out:  docs/database/transactions.html                    |   4 +-
out:  docs/database/utilities.html                       |   4 +-
out:  docs/dbmgmt/db_commands.html                       |   6 +-
out:  docs/dbmgmt/forge.html                             |   4 +-
out:  docs/dbmgmt/index.html                             |   4 +-
out:  docs/dbmgmt/migration.html                         |  33 +-
out:  docs/dbmgmt/seeds.html                             |   4 +-
out:  docs/extending/authentication.html                 |   4 +-
out:  docs/extending/basecontroller.html                 |   4 +-
out:  docs/extending/common.html                         |   4 +-
out:  docs/extending/composer_packages.html              |   4 +-
out:  docs/extending/contributing.html                   |   4 +-
out:  docs/extending/core_classes.html                   |   8 +-
out:  docs/extending/events.html                         |   4 +-
out:  docs/extending/index.html                          |   4 +-
out:  docs/general/ajax.html                             |   4 +-
out:  docs/general/caching.html                          |   4 +-
out:  docs/general/common_functions.html                 |   4 +-
out:  docs/general/configuration.html                    |  14 +-
out:  docs/general/environments.html                     |  12 +-
out:  docs/general/errors.html                           |   4 +-
out:  docs/general/helpers.html                          |   4 +-
out:  docs/general/index.html                            |   4 +-
out:  docs/general/logging.html                          |   4 +-
out:  docs/general/managing_apps.html                    |   4 +-
out:  docs/general/modules.html                          |  38 ++-
out:  docs/general/urls.html                             |  12 +-
out:  docs/genindex.html                                 |   4 +-
out:  docs/helpers/array_helper.html                     |   4 +-
out:  docs/helpers/cookie_helper.html                    |   4 +-
out:  docs/helpers/date_helper.html                      |   4 +-
out:  docs/helpers/filesystem_helper.html                |   4 +-
out:  docs/helpers/form_helper.html                      |   4 +-
out:  docs/helpers/html_helper.html                      |   4 +-
out:  docs/helpers/index.html                            |   4 +-
out:  docs/helpers/inflector_helper.html                 |   4 +-
out:  docs/helpers/number_helper.html                    |   4 +-
out:  docs/helpers/security_helper.html                  |   4 +-
out:  docs/helpers/test_helper.html                      |   4 +-
out:  docs/helpers/text_helper.html                      |   4 +-
out:  docs/helpers/url_helper.html                       |   4 +-
out:  docs/helpers/xml_helper.html                       |   4 +-
out:  docs/incoming/content_negotiation.html             |   4 +-
out:  docs/incoming/controllers.html                     |   4 +-
out:  docs/incoming/filters.html                         |  69 ++--
out:  docs/incoming/incomingrequest.html                 |   4 +-
out:  docs/incoming/index.html                           |   4 +-
out:  docs/incoming/message.html                         |   4 +-
out:  docs/incoming/methodspoofing.html                  |   4 +-
out:  docs/incoming/request.html                         |   4 +-
out:  docs/incoming/restful.html                         |   4 +-
out:  docs/incoming/routing.html                         |   4 +-
out:  docs/index.html                                    |   4 +-
out:  .../installation/backward_compatibility_notes.html |  13 +-
out:  docs/installation/index.html                       |   8 +-
out:  docs/installation/installing_composer.html         |   9 +-
out:  docs/installation/installing_manual.html           |   4 +-
out:  docs/installation/repositories.html                |   4 +-
out:  docs/installation/running.html                     | 153 +++++----
out:  docs/installation/troubleshooting.html             |   4 +-
out:  docs/installation/upgrade_404.html                 |   4 +-
out:  docs/installation/upgrade_405.html                 |   4 +-
out:  docs/installation/upgrade_410.html                 |   4 +-
out:  docs/installation/upgrade_412.html                 |   4 +-
out:  docs/installation/upgrade_413.html                 |   4 +-
out:  docs/installation/upgrade_414.html                 |   4 +-
out:  docs/installation/upgrade_415.html                 |   4 +-
out:  docs/installation/upgrade_416.html                 |   4 +-
out:  docs/installation/upgrade_417.html                 |   4 +-
out:  docs/installation/upgrade_418.html                 |   4 +-
out:  docs/installation/upgrade_420.html                 |   4 +-
out:  docs/installation/upgrade_421.html                 |   4 +-
out:  docs/installation/upgrade_4210.html                |   4 +-
out:  docs/installation/upgrade_4211.html                |   4 +-
out:  docs/installation/upgrade_4212.html                |   4 +-
out:  docs/installation/upgrade_4***.html                 |   4 +-
out:  docs/installation/upgrade_423.html                 |   4 +-
out:  docs/installation/upgrade_425.html                 |   4 +-
out:  docs/installation/upgrade_426.html                 |   4 +-
out:  docs/installation/upgrade_427.html                 |   4 +-
out:  docs/installation/upgrade_428.html                 |   4 +-
out:  docs/installation/upgrade_430.html                 |   4 +-
out:  docs/installation/upgrade_431.html                 |   4 +-
out:  docs/installation/upgrade_432.html                 |   4 +-
out:  docs/installation/upgrade_433.html                 |   4 +-
out:  docs/installation/upgrade_434.html                 |   4 +-
out:  docs/installation/upgrade_435.html                 |   4 +-
out:  docs/installation/upgrade_436.html                 |   4 +-
out:  docs/installation/upgrade_437.html                 |   4 +-
out:  docs/installation/upgrade_438.html                 |   4 +-
out:  docs/installation/upgrade_440.html                 |  85 ++++-
out:  docs/installation/upgrade_441.html                 | 359 ++++++++++++++++++++
out:  docs/installation/upgrade_442.html                 | 350 +++++++++++++++++++
out:  docs/installation/upgrade_4xx.html                 |   4 +-
out:  docs/installation/upgrade_configuration.html       |   4 +-
out:  docs/installation/upgrade_controllers.html         |   4 +-
out:  docs/installation/upgrade_database.html            |   4 +-
out:  docs/installation/upgrade_emails.html              |   4 +-
out:  docs/installation/upgrade_encryption.html          |   4 +-
out:  docs/installation/upgrade_file_upload.html         |   6 +-
out:  docs/installation/upgrade_html_tables.html         |   4 +-
out:  docs/installation/upgrade_localization.html        |   4 +-
out:  docs/installation/upgrade_migrations.html          |   4 +-
out:  docs/installation/upgrade_models.html              |   4 +-
out:  docs/installation/upgrade_pagination.html          |   4 +-
out:  docs/installation/upgrade_responses.html           |   4 +-
out:  docs/installation/upgrade_routing.html             |   4 +-
out:  docs/installation/upgrade_security.html            |   4 +-
out:  docs/installation/upgrade_sessions.html            |   4 +-
out:  docs/installation/upgrade_validations.html         |   6 +-
out:  docs/installation/upgrade_view_parser.html         |   4 +-
out:  docs/installation/upgrade_views.html               |   4 +-
out:  docs/installation/upgrading.html                   |   6 +-
out:  docs/intro/credits.html                            |   4 +-
out:  docs/intro/index.html                              |   4 +-
out:  docs/intro/psr.html                                |   4 +-
out:  docs/intro/requirements.html                       |  10 +-
out:  docs/libraries/caching.html                        |   4 +-
out:  docs/libraries/cookies.html                        |   4 +-
out:  docs/libraries/curlrequest.html                    |  26 +-
out:  docs/libraries/email.html                          |  25 +-
out:  docs/libraries/encryption.html                     |   4 +-
out:  docs/libraries/file_collections.html               |   4 +-
out:  docs/libraries/files.html                          |   4 +-
out:  docs/libraries/honeypot.html                       |   4 +-
out:  docs/libraries/images.html                         |   4 +-
out:  docs/libraries/index.html                          |   4 +-
out:  docs/libraries/official_packages.html              |   4 +-
out:  docs/libraries/pagination.html                     |   4 +-
out:  docs/libraries/publisher.html                      |  10 +-
out:  docs/libraries/security.html                       |   9 +-
out:  docs/libraries/sessions.html                       |   4 +-
out:  docs/libraries/throttler.html                      |   4 +-
out:  docs/libraries/time.html                           |   4 +-
out:  docs/libraries/typography.html                     |   4 +-
out:  docs/libraries/uploaded_files.html                 |   4 +-
out:  docs/libraries/uri.html                            |   4 +-
out:  docs/libraries/user_agent.html                     |   4 +-
out:  docs/libraries/validation.html                     |  13 +-
out:  docs/license.html                                  |   4 +-
out:  docs/models/entities.html                          |   4 +-
out:  docs/models/index.html                             |   4 +-
out:  docs/models/model.html                             |   4 +-
out:  docs/objects.inv                                   | Bin 11501 -> 11607 bytes
out:  docs/outgoing/alternative_php.html                 |   4 +-
out:  docs/outgoing/api_responses.html                   |   4 +-
out:  docs/outgoing/index.html                           |   4 +-
out:  docs/outgoing/localization.html                    |   4 +-
out:  docs/outgoing/response.html                        |   6 +-
out:  docs/outgoing/table.html                           |   4 +-
out:  docs/outgoing/view_cells.html                      |   4 +-
out:  docs/outgoing/view_decorators.html                 |   4 +-
out:  docs/outgoing/view_layouts.html                    |   4 +-
out:  docs/outgoing/view_parser.html                     |   4 +-
out:  docs/outgoing/view_renderer.html                   |   4 +-
out:  docs/outgoing/views.html                           |   4 +-
out:  docs/php-modindex.html                             |   4 +-
out:  docs/search.html                                   |   4 +-
out:  docs/searchindex.js                                |   2 +-
out:  docs/testing/benchmark.html                        |   4 +-
out:  docs/testing/controllers.html                      |   4 +-
out:  docs/testing/database.html                         |   4 +-
out:  docs/testing/debugging.html                        |   4 +-
out:  docs/testing/fabricator.html                       |   4 +-
out:  docs/testing/feature.html                          |   4 +-
out:  docs/testing/index.html                            |   4 +-
out:  docs/testing/mocking.html                          |   4 +-
out:  docs/testing/overview.html                         |  10 +-
out:  docs/testing/response.html                         |   4 +-
out:  docs/tutorial/conclusion.html                      |   4 +-
out:  docs/tutorial/create_news_items.html               |  86 ++---
out:  docs/tutorial/index.html                           |   6 +-
out:  docs/tutorial/news_section.html                    |  70 ++--
out:  docs/tutorial/static_pages.html                    | 111 +++---
out:  262 files changed, 2390 insertions(+), 791 deletions(-)
out:  create mode 100644 CodeIgniter4.4.1.epub
out:  create mode 100644 CodeIgniter4.4.2.epub
out:  create mode 100644 docs/changelogs/v4.4.1.html
out:  create mode 100644 docs/changelogs/v4.4.2.html
out:  create mode 100644 docs/installation/upgrade_441.html
out:  create mode 100644 docs/installation/upgrade_442.html
==============================================
✅ Successfully executed commands to all host.
==============================================
```
